Use /tmp instead of padd.sh dir to store temp files
pi-hole/PADD pull request #211
Opened 2022-03-25 18:21 UTC by yubiuser

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits. Pi-hole enforces the [DCO](https://docs.pi-hole.net/guides/github/contributing/).

---
**What does this PR aim to accomplish?:**
With https://github.com/pi-hole/PADD/pull/168 we chdir to the dir `padd.sh` is stored in to prevent littering the files we create (`PADD.pid` and `piHoleVersion`). In the PR we already disused if it wouldn't be better to use `/tmp` as it should always be user-writable, but assumed the dir where `padd.sh` is located would be user-writable as well.
However, users copied `padd.sh` to dirs they have no write privileges too (''/usr/bin`), https://github.com/pi-hole/PADD/issues/207.

This PR creates our files in the local temp dir (probably always `/tmp`), which should be always user-writable.

2022-03-26 07:47 UTC, DL6ER reviewed
I'd consider it cleaner to create a subdirectory instead of putting it straight into `/tmp`

2022-03-26 14:01 UTC, yubiuser commented
Like this?

2022-03-26 21:07 UTC, DL6ER requested changes
Mind case-sensitivity of paths

`mkdir $tmpdir/PADD/` vs. `cd "$tmpdir/padd/"`

2022-03-27 06:36 UTC, DL6ER commented on padd.sh
> +mkdir -p "$tmpdir/PADD/"
```suggestion
mkdir -p "$tmpdir/padd/"
```

2022-03-27 07:17 UTC, DL6ER commented
I'm wondering if this would work when multiple users try to start PADD on the same machine for themselves? The first one will be the owner of the directory.

2022-03-27 08:43 UTC, yubiuser commented
How likely is it that multiple users try to start PADD? Anyhow, we could use `mktemp -d` which should create unique directories, or?

2022-03-27 10:51 UTC, DL6ER commented
Yes, `mktemp -d` indeed sounds like the optimal solution, could also something like
```
mktemp -d PADD_XXXX
```
just to ensure `PADD` will be in its name

2022-03-27 13:11 UTC, yubiuser commented
With the new code, started `padd.sh` twice (double ssh login, but same user).

```
rockpi@rockpi-4b:/tmp$ ls -lha
total 16K
drwxrwxrwt 15 root   root    360 Mar 27 15:05 .
drwxr-xr-x 19 root   root   4.0K Jan 25  2021 ..
drwx------  2 rockpi rockpi   80 Mar 27 15:04 padd.OKl
drwx------  2 rockpi rockpi   80 Mar 27 15:03 padd.Tp7
```

2022-03-27 13:12 UTC, yubiuser commented
Omitting `--tempdir` resulted in dir creation in my home dir...

2022-03-27 16:13 UTC, dschaper requested changes

2022-03-27 16:13 UTC, dschaper commented on padd.sh
> +cd "$tmpdir" || {
Use `pushd` and `popd` instead. `cd` can leave an unknown state with subshells.

2022-03-27 16:43 UTC, yubiuser commented
Thinking about random dirs again makes me think this is not a good idea: The whole idea of saving the file is to re-use the information later again. If on each restart the working dir changes, padd will never access the same file again. I'll construct the path by usin `id -u` which should prevent collision by different users as well.

2022-05-21 21:18 UTC, dschaper commented
pid's should go in the `/var` tree and be cleaned on exit of the shell. (Probably something like a 'trap' would be best.)

Why does the piholeVersion file need to stay around?

2022-05-22 11:18 UTC, yubiuser commented
We don't create a `pid` file anymore since https://github.com/pi-hole/PADD/pull/197
(this branch needs to be rebased on latest development...)

`piholeVersion` was already part of the initial chronometer2->PADD PR without further explanation. Looking at the code, the file is used to store Pi-hole's version information as well as PADD version information. It's part of `GetVersionInformation()` which is executed withing `NormalPADD()` every 5 seconds. 
First thing  in `GetVersionInformation` is to check if the current date is the same as the date `piholeVersion` was updated and if so, skip the rest. What's happening further down is 

https://github.com/pi-hole/PADD/blob/831f3fce65391449b335cef1f72d6e827f2c510c/padd.sh#L539

where the script contacts GH's API to get the latest PADD version tag. By using a local file and updating it only once a day we prevent connecting the API every 5 seconds for every user running PADD.

For that reason I do still see a valid reason to keep the file

2022-05-22 11:51 UTC, yubiuser commented
Rebased on latest `development`. `*.pid` file is not created anymore. But `pushd` and `popd` are `bash` built-ins, so we need to go back to `cd`
https://stackoverflow.com/questions/5193048/bin-sh-pushd-not-found

2022-05-22 20:33 UTC, dschaper commented
> It's part of `GetVersionInformation()` which is executed withing `NormalPADD()` every 5 seconds.
> First thing in `GetVersionInformation` is to check if the current date is the same as the date `piholeVersion` was updated and if so, skip the rest.

Okay, I think it should be deleted (or tmp file that isn't kept) for the reason that with the file deleted then every start of PADD will check to see if there is a new version. As it is now you have to delete that file and restart to pull the new version or wait 1 day for it to time out. With it gone then you only need to restart to get the new version.

2022-05-22 21:18 UTC, yubiuser commented
My explanation was not comprehensive: it already is deleted on every PADD restart. I just focused on why the file exists at all.

https://github.com/pi-hole/PADD/blob/831f3fce65391449b335cef1f72d6e827f2c510c/padd.sh#L1027-L1041

2022-05-22 21:31 UTC, dschaper approved these changes

2022-05-22 21:33 UTC, dschaper commented
LGTM

2022-05-22 22:06 UTC, merged