Use padd.sh URLs
pi-hole/PADD pull request #213
Opened 2022-04-07 21:18 UTC by dschaper

**By submitting this pull request, I confirm the following:** 

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [ ] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
**What does this PR aim to accomplish?:**

Move to `https://install.padd.sh` URL.

2022-04-08 04:49 UTC, yubiuser requested changes
We should update, clean and fix the wiki before merging this to master

2022-04-08 04:49 UTC, yubiuser commented on README.md
> +*Answers to frequently asked questions can be found in this repo’s [wiki](https://github.com/pi-hole/PADD/wiki/FAQ).*
We don't have a FAQ....

2022-04-18 19:03 UTC, yubiuser requested changes
L7: The image does not exist anymore. 

Additionally, before we merge this, we need to update the wiki as well (contains old links...)

2023-01-08 17:49 UTC, rdwebdesign commented
Should we reopen this PR?

2023-01-08 23:06 UTC, dschaper commented
That's up to you all, the domain is there and available to use.

2023-01-08 23:16 UTC, rdwebdesign commented
I will reopen the PR. 

My opinion is: we should use the domain.
As always, I want to hear the opinion of the other team members.

2023-01-15 18:51 UTC, rdwebdesign commented
The proposed change on this PR is simple, but there are a lot of conflicts here.

2023-01-15 19:38 UTC, yubiuser approved these changes

2023-01-15 19:40 UTC, merged