Try to use the CLI password for logins
pi-hole/PADD pull request #392
Opened 2024-06-20 17:45 UTC by DL6ER

# What does this implement/fix?

This PR accompanies PR https://github.com/pi-hole/FTL/pull/1999

---

**Related issue or feature (if applicable):** N/A

**Pull request in [docs](https://github.com/pi-hole/docs) with documentation (if applicable):** N/A

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

## Checklist:

- [x] The code change is tested and works locally.
- [x] I based my code and PRs against the repositories `developmental` branch.
- [x] I [signed off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits. Pi-hole enforces the [DCO](https://docs.pi-hole.net/guides/github/dco/) for all contributions
- [x] I [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) all my commits. Pi-hole requires signatures to verify authorship
- [x] I have read the above and my PR is ready for review.

2024-06-21 17:10 UTC, rdwebdesign requested changes

2024-06-21 17:10 UTC, rdwebdesign commented on padd.sh
> +            if [ "${availabilityResonse}" = 200 ]; then
The same typo identified by promofaux on the other PR:

```suggestion
            if [ "${availabilityResponse}" = 200 ]; then
```

2024-06-22 10:42 UTC, PromoFaux commented
Tested with and without `webserver.api.cli_pw` enabled

disabled = prompts for password and then works
enabled = works without password prompt

👍 

Happy to approve once suggestions resolved

2024-06-22 18:58 UTC, rdwebdesign approved these changes

2024-06-27 16:29 UTC, PromoFaux approved these changes

2024-06-29 12:41 UTC, yubiuser requested changes
Could you please rebase on latest `PADD_FTLv6`.
I noticed that the status codes in `DeleteSession` do not match them in https://github.com/pi-hole/PADD/pull/247 and the current documentation https://ftl.pi-hole.net/development-v6/docs/#delete-/auth

2024-06-29 19:10 UTC, DL6ER commented
Sure, this PR would only merge the `diff`, so it doesn't matter but I rebased nonetheless.

2024-06-29 19:56 UTC, yubiuser approved these changes

2024-06-30 18:26 UTC, merged